version: '3.8'


services:
  nginx:
    image: nginx:1.13.1
    restart: always 
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html

  dockergen:
    image: jwilder/docker-gen:0.7.3
    restart: always 
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxied containers. 
# docker network create --driver overlay --subnet 172.16.0.0/24 --attachable nginx-proxy
# добавить rootCA.crt в Доверенные корневые сертификаты -> certificate (mmc.exe -> сертификаты)

networks:
  default:
    name: nginx-proxy
    external: true
